### Importando bibliotecas

In [3]:
import numpy as np
import tensorflow as tf

In [6]:
# Criando matrizes com valores zerados.

Z = tf.zeros([3,4,4], dtype= tf.int64)

Z

<tf.Tensor: shape=(3, 4, 4), dtype=int64, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)>

In [7]:
# Reshape em Tensor

Z_reshape = tf.reshape(tensor=Z, shape = [2,4,6])

Z_reshape

<tf.Tensor: shape=(2, 4, 6), dtype=int64, numpy=
array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]], dtype=int64)>

In [8]:
# Criando matriz aleatória com valores guasianos

T = tf.random.uniform([5,4],dtype= tf.float32)

T

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.24089742, 0.69551647, 0.64329386, 0.7805929 ],
       [0.6042843 , 0.01832271, 0.34190464, 0.6979784 ],
       [0.50510335, 0.8964118 , 0.9347403 , 0.27228248],
       [0.9122423 , 0.6013452 , 0.02983654, 0.68961024],
       [0.03126717, 0.8853235 , 0.5645304 , 0.10226202]], dtype=float32)>

In [9]:
# mudando tipo de dado

T_cast_int = tf.cast(T,dtype=tf.int64)

T_cast_int

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)>

In [10]:
# multiplicação de matrizes

A = tf.constant( [[5,4],
                  [3,2]],
                    dtype= tf.int32)

V = tf.constant( [[2],
                  [3]],
                  dtype= tf.int32)

A_V_result = tf.matmul(A,V)

A_V_result

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[22],
       [12]])>