<a href="https://colab.research.google.com/github/CharlesPrado23/Bootcamp_TurmaNoite/blob/main/Conteudo_02/Exerc%C3%ADcios_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [5]:
### Questão 1
### Use o método np.unique para retornar um array sem duplicatas
# names2 = np.unique(names)
# names2
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [17]:
### Questão 2
### crie uma matriz (4,3) usando o método np.random.randn(x,y)
matrix = np.random.randn(4,3)
matrix

array([[ 0.89565995, -0.26572406,  0.21380595],
       [ 0.91641644,  0.80251013, -0.2719389 ],
       [-0.58536643,  0.52512834,  1.39706325],
       [-0.03355748, -0.20261604,  0.31398691]])

In [22]:
### Questão 3 
### Retorne os elementos entre as linhas 2 e 3 ; e entre as colunas 1 e 2 
### Use o conceito de slice e armazene o resultada em outro array
matrix2 = matrix[2:4,1:3]
matrix2


array([[ 0.52512834,  1.39706325],
       [-0.20261604,  0.31398691]])

In [25]:
### Questão 4 
### Calcule o valor médio da matriz da Questão 2 
### Calcule o valor médio da matriz da Questão 2 na direção horizontal
### Calcule o valor médio da matriz da Questão 2 na direção vertical
matrix.mean()

array([0.29828812, 0.2148246 , 0.4132293 ])

In [26]:
matrix.mean(axis=0)

array([0.29828812, 0.2148246 , 0.4132293 ])

In [27]:
matrix.mean(axis=1)

array([0.28124728, 0.48232922, 0.44560839, 0.0259378 ])

In [24]:
np.mean(matrix)

0.3087806732282377

In [ ]:
### Questão 5
### usando o método arange , crie um array com 50 posições 
### Modifique todos os valores para o valor igual a 1 
### Usando o método reshape crie uma matriz (10,5)


In [29]:
matrix3 = np.arange(0,50)
len(matrix3)

50